### ISSUE TITLE
Languages with multiple treebanks

### ISSUE THREAD

**Issue by fginter** [ufal/conll2017#12]
I think it was left undecided what to do with languages that have multiple treebanks. My relatively strong opinion is to treat them separately, i.e. not to pool the test sets. Participants can pool the training data any way they like, naturally. My primary reason is that it is well known the treebanks are not necessarily all that compatible and that will not be fully remedied before the ST. If we pool the test sets, the systems will be punished for differences between the individual treebanks. This would have the effect of 1) underestimating the learning capability of the parsers  2) underestimating the actual performance of the parsers by superimposing test data noise over the results.

I think getting a good estimate of the real performance of state-of-the-art parsers on the data would be an important outcome of the task, and we should try to avoid external measurement errors. I think it would not be good if we have to write into the ST report paper that "numbers for language X seem to be quite low, but that is probably because treebanks X.1 and X.2 are in the end quite different in the details and so we do not really know how well we can parse language X".

**Comment by dan-zeman** [comment]
This issue is actually twofold. Part one is whether we want to report separate numbers for each treebank. I believe we do, exactly for the reasons put by @fginter.

Part two is whether we want to count each treebank separately in the overall macro-average for system ranking. Here I am not so sure. We can of course keep the same stance, say that learning to parse two different treebanks of one language are two different tasks, and the system should get same credit as if learning two totally different languages. But I think I would prefer one language to only have one vote in the overall average, and all treebanks with the same language code would first be pre-averaged locally. (Perhaps macro average again.)

**Comment by fginter** [comment]
Myself, I would not complicate the results by local macro-averaging of languages. In the end, we are ranking the systems by how well they can learn to parse treebanks, and the overall average, as a number, is IMHO not particularly meaningful, beyond providing the ranking. But if you feel strongly about it, I'm fine with the local averaging too... Anyone?

**Comment by foxik** [comment]
I do not have a strong oppinion on local macro-averaging myself. After some thought, I would probably not locally macro-average them -- to obtain good results, the participants will probably have to try using training data for all corpora with the same language code at the same time and employ some domain adaptation, so it seems fine for awarding them "points" for doing so.

**Comment by dan-zeman** [comment]
I don't feel strongly about it. And, on the second thought, I would also lean towards the easier solution, i.e. one macro-average over all test sets. I am closing the issue now; others feel free to reopen if you want to cast your vote against this decision.
