### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by jnivre** [ufal/conll2017#6]
I would strongly advocate using a UD-specific main evaluation metric that focuses on content word dependencies. Please see http://stp.lingfil.uu.se/~nivre/docs/udeval-cl.pdf for some of the arguments for such a metric and a concrete proposal.

**Comment by foxik** [comment]
Great that you have a concrete proposal. I have added the CNC to the proposal (without deciding yet).

There are probably nearly no CNC results in the existing papers, but that is of no concert for a shared task. Conversely, a shared task would be the best place where to promote the CNC measure :-)

OT: This means I should add CNC to UDPipe and to the benchmark&evaluation UD page (I have been on several-week-long vacation and I will probably be on vacation next week too, but I still have it on top of my list).

**Comment by jnivre** [comment]
Note that CNC is just a first proposal, and it may be necessary to tweak it a little bit. For example, "compound" is a relation that should probably be excluded because of cross-linguistic variation but is currently included. But I like the idea of using the CoNLL shared task to promote a new metric, so hopefully we could put together a working group for this.

**Comment by foxik** [comment]
I updated the proposal to state that we want to use some kind of content-word-based evaluation metrics and that it needs to be devised, with CNC as a starting point.

**Comment by martinpopel** [comment]
I don't understand how is [CNC](http://stp.lingfil.uu.se/~nivre/docs/udeval-cl.pdf) exactly computed.
- The [proposal](https://github.com/ufal/conll2017/blob/672722c7097744a68eb1609942da12c5dd13806b/proposal/proposal.md#metric-focused-on-ud-content-word-dependencies) says "The CNC is a modification of LAS, where the dependency relations in the Punct and Func subset are ignored." That means `CNC = correct / all`, where `all` is the number words with gold deprel not in `aux|auxpass|case|cc|cop|det|mark|neg` and `correct` is the number of such words which have correct parent and deprel assigned by the parser.
- The [CNC paper](http://stp.lingfil.uu.se/~nivre/docs/udeval-cl.pdf) says CNC is a "labeled F-score over all relations except
  Punct and Funct", but an exact formula is missing. Should we compute precision and recall for each deprel separately and then somehow average it?

The problem of the first definition is that it can be cheated. There is no motivation for the parsers to produce Punct and Func deprels. So even if the parser is quite sure that a given word is a function word, it is better to label it with some non-Func deprel, as this can only improve CNC.

**Comment by dan-zeman** [comment]
- ccorrect = number of nodes whose system HEAD matches the gold HEAD, system DEPREL matches the gold DEPREL, and the gold DEPREL is on the list of content relations
- csystem = number of nodes whose system DEPREL is on the list of content relations
- cgold = number of nodes whose gold DEPREL is on the list of content relations
- P = ccorrect / csystem
- R = ccorrect / cgold
- "THE SCORE" = F = 2PR / (P+R)

It could be extended so that the remaining (non-content) relations are evaluated separately in a similar way, then the two scores are combined with different weights (weight TBD). But even if the other relations are not evaluated, the system should not spread content relations everywhere, because that means low precision => low F.

The exact list of content relations is also TBD.

**Comment by martinpopel** [comment]
Thanks Dan for providing the exact CNC formula.

I agree it is a good idea to exclude punctuation (as it is often done in LAS) because
- It is not annotated consistently (the UD guidelines for punctuation are not detailed enough).
- It is probably not so important for downstream tasks.

I don't like the idea that **CNC completely ignores all function words** and that **CNC should be the official CoNLL 2017 metric**.
I think function words are annotated quite consistently in UD and their correct attachment and deprel is crucial for several NLP tasks.
We can provide CNC as an additional metric, but I am not sure if we want to make it the official metric and thus make the parsers optimize for it. 

If we think function words are less important (which is true for some NLP tasks), we can put a lower weight on them when computing LAS (which is very similar to combining two F-scores as Dan suggested).

I've read the [CNC proposal](http://stp.lingfil.uu.se/~nivre/docs/udeval-cl.pdf), but I am not convinced about it supposed advantages. If we take the approach to extreme, we could exclude modifiers from evaluation because in German these are frequently part of compound nouns, so German has lower LAS scores because the easy-to-parse modifiers are not considered as separate words. Or we could exclude all (subject) pronouns from evaluation because there are pro-drop languages.

I think it is quite OK that LAS is higher for some languages because those languages have e.g. many easy-to-parse determiners. At least, I don't see why LAS should be an unfair metric for comparing parsers. On the other hand I could imagine CNC-tuned parsers perform very badly on function words.

**Comment by fginter** [comment]
FWIW, I think CNC is fine as defined by Dan's formulas. I can see why not everyone likes CNC, though. We just need to decide, so others please chip in with your votes. :)

**Comment by jnivre** [comment]
We have already agreed (I think) that we are not going to score the entire grammatical representations (tags, features, dependencies) but focus on syntactic dependencies. This means that we have already decided to omit features like definiteness, passive voice, etc. IF these are encoded morphologically. Adopting CNC is (in my view) only the logical consequence of this, that is, omitting them ALSO if they are encoded by free grammatical morphemes instead of bound ones. Needless to say, we will of course report LAS as well, but it will not be the main metric because it is not suitable for the UD representation, where function words are put on a more equal footing with bound grammatical morphemes. Also, as Dan points out, we need to work on the exact list of relations to be included in CNC. It is dubious whether "compound" should be included, for example. In addition, we probably want to define metrics over other types of relations as well.

**Comment by foxik** [comment]
@jnivre I understand your view.

However, in my opinion, the shared task is about _parsing_, which is why we don't evaluate the POS tags, lemmas and morphological features. The participants should therefore be able to parse as accurately as possible, even if some dependencies are easier in some languages and encode some morphological features -- it is still the parser which has to discover them, not a POS tagger/lemmatizer/morphological analyzer. So from my point of view it makes sense to evaluate the full LAS, even including punctuation, and I do not think it would be unsuitable for UD representation -- on the contrary, it seems suitable to me, as the punctuation and functional word annotation in UD is consistent across languages.

So one other possiblity would be to report both LAS and CNC-like (CNC with additional changes) scores, with LAS being the primary metric at this point. We could then "evaluate" the effect of CNC-like metric in the overview paper (maybe even modify the exact rules of the metric according to the data we will have) and, if we decide so, suggest that the CNC-like metrics should be used in the future (and explain our reasoning).

**Comment by dan-zeman** [comment]
I am quite undecided myself but the time is running and we have to arrive at a decision. One thing that comes on mind—if we want to really load-test CNC, we should make it the main system ranking metric and motivate people to optimize their systems towards CNC. Then we can make suggestions for future (and explain our reasoning).

So I vote for CNC (I think we don't even have to have the exact list of deprels ready by the time we submit the proposal).

**Comment by foxik** [comment]
One disadvantage is that the models trained for CNC will probably be of no other use than for the shared task -- we will probably not release UDPipe models trained for CNC, because they probably parse functional words wrongly; instead, we will train another models against LAS and release those. But that is probably fine, as the models released with UDPipe have to perform many other tasks (at least POS tagging and lemmatization).

So personally I like LAS more, but I understand the motivation behind CNC (and also the fact that CNC is novel [compared to LAS] and may be more interesting for other people).

**Comment by jnivre** [comment]
This is clearly an empirical question, but I am not at all convinced that models optimized for CNC will have low accuracy on function words. In addition, people can choose to optimise a joint objective. As you know, I am in favor of (something like) CNC, but I think the shared task proposal could leave this open. Or rather, we could say that we plan to use both standard LAS and UD-tailored metrics, and that we need to more investigations to decide which is going to be the main metric.

**Comment by foxik** [comment]
@jnivre Fair point. The situation I am describing (wrong parsing of function words) is definitely not guaranteed to happen. My (completely personal) intuition is that using CNC during _training time_ will improve the CNC on the test set (compared to training with LAS and then evaluating using CNC; a bit analogously to using BLEU during MT training). If this is so, the models then may choose to parse function words just enough to "not get in the way" (especially not marking them as non-function words).

But I am not saying that this is a reason for not adopting CNC -- as noted above, the CoNLL'17 and UDPipe models have different purpose anyway :-)

**Comment by martinpopel** [comment]
I agree with @jnivre that an ideal metric should score the entire grammatical representations (tags, features, dependencies), i.e. including morpho-analysis, but we cannot use this in CoNLL 2017, where we want to focus on parsing only. Parsing of functional words is important for many tasks (and it still belongs to parsing as @foxik noted), so I think it should be reflected in the parsing metric. I would prefer LAS for its simplicity (there will be many other difficulties and novelties in CoNLL2017 anyway).
If we decide to use something CNC-like as the main metric, I would strongly suggest:
- define it more generally as a weighted average of F-scores of four categories of words: core dependents, non-core dependents, functional words, punctuation
- for CoNLL2017 set the weights: punctuation=0, functional = small but non-zero constant

I think no one can predict how all the _various_ parsers will handle functional words if optimized for CNC only (and why would someone use a joint objective CNC+LAS if it does not improve the official CNC?). I hope that the small but non-zero constant for functional words in my proposal makes sure function words are handled reasonably (so it can be used even for training the public-use UDPipe models) and it can be very close to the CNC results (so results across languages are more comparable, although I still don't see any advantage in this point).

**Comment by dan-zeman** [comment]
As @jnivre suggests above, the proposal now says that we will compute both metrics but we need more investigation to see whether it is reasonable to make the UD-specific metric the main metric of the task. That means that we have time roughly until December (when the rules of the task should be published) to finalize the new metric (including lists of relations and weights), implement it in UDPipe, test it etc.

I suggest to leave this issue open until we make the decision.
